### ISSUE TITLE
Refactor propsToTrim with Transient Props

### ISSUE THREAD

**Issue by johann-napa** [napagroup/grape-ui-react#90]
Transient Props is a new concept in styled-components that indicates the prop should not return on the DOM.  We have a function in grape-ui that does this called propsToTrim.  However, transient props may be the way to go.

### Possible benefits:

- Reduces package size by removing propsToTrim

- Change the styled.js/component.js approach we have in place

### Challenges:

- How do transient props work for spread props?

https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c

**Comment by ryanespin** [comment]
We will not be moving forward with this issue.
